server:
  port: 8503
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
feign:
  sentinel:
    enabled: true
spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.75.132:8858
    openfeign:
      lazy-attributes-resolution: true
      client:
        config:
          default:
            connectTimeout: 30000
            readTimeout: 30000
            loggerLevel: basic
  data:
    redis:
      host: 192.168.75.132
      port: 6379
      database: 0
      timeout: 1800000
      password:
      jedis:
        pool:
          max-active: 20 #最大连接数
          max-wait: -1    #最大阻塞等待时间(负数表示没限制)
          max-idle: 5    #最大空闲
          min-idle: 0     #最小空闲
    mongodb:
      host: 192.168.75.132
      port: 27017
      database: tingshu #指定操作的数据库
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.75.132:33310/tingshu_user?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: 123456
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 60000
      idle-timeout: 500000
      max-lifetime: 540000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# wechat:
#   login:
#     #小程序授权登录
#     appId: wxffafd4cb6a9c31a9  # 小程序微信公众平台appId
#     appSecret: 054f93758f2e5f0fdb3e4cf9ef69e854  # 小程序微信公众平台api秘钥
wx:
  miniapp:
    appid: wxffafd4cb6a9c31a9
    secret: 054f93758f2e5f0fdb3e4cf9ef69e854
    msgDataFormat: JSON
seata:
  tx-service-group: tx_glsx_group
  service:
    vgroup-mapping:
      tx_glsx_group: default
    grouplist:
      default: 192.168.75.132:8091